name: Lint, Build and Test
on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - master
  workflow_dispatch:
    branches:
      - master
  push:
    branches:
      - master

env:
  SECRET: ${{ secrets.SECRET }}
  MONGO_URI: ${{ secrets.MONGO_URI}}
  WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
  PORT: 4000
  CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
  VITE_API_URL: ""

jobs:
  test_build:
    runs-on: ubuntu-latest
    name: Build and Test
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "yarn"
          cache-dependency-path: api/yarn.lock

      - name: Install dependencies (api - backend)
        working-directory: ./api
        run: yarn

      - name: Prettier (api - backend)
        working-directory: ./api
        run: yarn format

      - name: Lint (api - backend)
        working-directory: ./api
        run: yarn lint

      - name: Build (api - backend)
        working-directory: ./api
        run: yarn build

      - name: Test (api - backend)
        working-directory: ./api
        run: yarn test

      - name: Install dependencies (app - frontend)
        working-directory: ./app
        run: yarn

      - name: Prettier (app - frontend)
        working-directory: ./app
        run: yarn format

      - name: Lint (app - frontend)
        working-directory: ./app
        run: yarn lint

      - name: Build (app - frontend)
        working-directory: ./app
        run: yarn build

      - name: Test (app - frontend)
        working-directory: ./app
        run: yarn test

      - name: Start backend (e2e testing)
        working-directory: ./api
        run: yarn dev &

      - name: Start Cypress tests
        uses: cypress-io/github-action@v2
        with:
          config-file: cypress.config.ts
          working-directory: app
          browser: electron
          install: true
          build: yarn build
          wait-on: http://localhost:3000
          start: npx vite --host
          record: true
