name: Build and Test
on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - master
  workflow_dispatch:
    branches:
      - master
  push:
    branches:
      - master

env:
  SECRET: ${{ secrets.SECRET }}
  MONGO_URI: ${{ secrets.MONGO_URI}}
  WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
  PORT: 4000

jobs:
  test_build:
    runs-on: ubuntu-latest
    name: Build and Test
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "yarn"
          cache-dependency-path: api/yarn.lock

      - name: Install dependencies (api - backend)
        working-directory: ./api
        run: yarn

      - name: Build (api - backend)
        working-directory: ./api
        run: yarn build

      - name: Test (api - backend)
        working-directory: ./api
        run: yarn test

      - name: Install dependencies (app - frontend)
        working-directory: ./app
        run: yarn

      - name: Build (app - frontend)
        working-directory: ./app
        run: yarn build

      - name: Test (app - frontend)
        working-directory: ./app
        run: yarn test

      - name: Start backend (e2e testing)
        run: |
          cd api
          yarn start

      - name: Start Cypress tests
        uses: cypress-io/github-action@v2
        with:
          working-directory: app
          wait-on: "http://localhost:4000"
          command-prefix: "yarn"
          start: "test:e2e:run"
          wait-on-timeout: "120000"
